# Uncomment this line to define a global platform for your project
 platform :ios, '13.0'

target 'LocafyApp' do
  # Comment this line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for VenderApp

  pod 'IQKeyboardManager'
  pod 'SDWebImage'
  pod 'RATreeView'
  pod 'SkyFloatingLabelTextField', '~> 3.0'
  pod 'NVActivityIndicatorView'
  pod 'RSSelectionMenu'
  pod 'SwiftyJSON'
  pod 'Cosmos'
  pod "RxSwift"
  pod 'RxCocoa'
  pod 'FSCalendar'
  pod 'Firebase/Messaging'
  pod 'libPhoneNumber-iOS', '~> 0.9.15'

  target 'LocafyAppTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'LocafyAppUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end

post_install do |installer_representation|
    installer_representation.pods_project.targets.each do |target|
        target.build_configurations.each do |config|
            config.build_settings['ONLY_ACTIVE_ARCH'] = 'NO'
            config.build_settings['BUILD_LIBRARY_FOR_DISTRIBUTION'] = 'YES'
            config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'] = '13.0'
        end
    end
end
